Release 2.1.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.2
+# This script was automatically generated by ACR v1.3
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -40,7 +40,7 @@ done
 }
 
 VPATH=`dirname ${0}`
-if [ "${VPATH}" = "." ]; then 
+if [ "${VPATH}" = "." ]; then
 	WODIS=current
 else
 	if [ "${VPATH}" = "${PWD}" ]; then
@@ -102,12 +102,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='radare2-bindings' ; VERSION='2.0.0' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
+ PKGNAME='radare2-bindings' ; VERSION='2.1.0' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
-                
+
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-bindings-2.0.0 to adapt to many kinds of systems.
+'configure' configures radare2-bindings-2.1.0 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -149,7 +149,7 @@ EOF2
 
 printf "
 Optional Features:
-  --with-ostype          Choose OS type (gnulinux windows darwin)  (USEROSTYPE=auto)
+  --with-ostype          Choose OS type (gnulinux windows darwin) (USEROSTYPE=auto)
 "
 printf "
 Some influential environment variables:
@@ -180,7 +180,7 @@ take_environ() {
 }
 
 show_version() {
-echo "radare2-bindings-2.0.0 configuration script done with acr v1.2.
+echo "radare2-bindings-2.1.0 configuration script done with acr v1.3.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -204,13 +204,13 @@ case $flag in
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   radare2-bindings"
-echo "VERSION:   2.0.0"
+echo "VERSION:   2.1.0"
 echo "LANGS:     c c++"
 echo "PKG-CONFIG:  r_core"
 echo "FLAGS:     --with-ostype=auto"
 	exit 0
 	;;
---cache-file) 
+--cache-file)
 	# ignored: acr have no cache
 	;;
 --build)
@@ -254,7 +254,7 @@ echo "FLAGS:     --with-ostype=auto"
 	MANDIR="$value"; ;;
 
 --with-ostype) if [ -z "${value}" ]; then USEROSTYPE="auto"; else USEROSTYPE="${value}" ; fi ;;
-*) if [ "$value" ]; then eval "`echo $flag2=$value`" ; 
+*) if [ "$value" ]; then eval "`echo $flag2=$value`" ;
 else echo ; echo "WARNING: Unknown flag '$flag'." >&2 ; echo ; fi ;;
 esac
 }
@@ -287,7 +287,7 @@ echo "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe test.c test.cxx a.out a.exe"
 
 
-: 
+
 COMPILER=CC
 printf "checking for c compiler... "
 HAVE_LANG_C=1
@@ -402,6 +402,7 @@ else
 if [ "$HOST_OS" = "darwin" ]; then
 USEROSTYPE="darwin"; fi; fi; fi; fi; fi; fi
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_core... '
 tmp=`${PKGCONFIG} --cflags r_core 2>/dev/null`
@@ -418,7 +419,7 @@ SEDFLAGS=" -e '"
 COUNT=0
 for A in ${ENVWORDS} ; do
 	[ "${A}" = VPATH ] && continue
-	[ "${A}" = srcdir ] && continue 
+	[ "${A}" = srcdir ] && continue
 	eval "VAR=\$${A}"
 	VAR="`echo ${VAR} | sed -e 's/\,/\\\,/g'`"
 	[ $COUNT = 10 ] && COUNT=0 && SEDFLAGS="${SEDFLAGS}' -e '"
