Release 5.1.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.8.1
+# This script was automatically generated by ACR v1.9.8
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -38,6 +38,11 @@ eval "$1_OS=\"$SPLIT_OS\""
 shift
 [ -z "$1" ] && break
 done
+}
+
+QUIET=0
+be_quiet() {
+	QUIET=1
 }
 
 VPATH=`dirname ${0}`
@@ -104,12 +109,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='radare2-bindings' ; VERSION='4.5.0-git' ; VERSION_MAJOR=4; VERSION_MINOR=5; VERSION_PATCH=0; VERSION_NUMBER=40500; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
+ PKGNAME='radare2-bindings' ; VERSION='5.1.0' ; VERSION_MAJOR=5; VERSION_MINOR=1; VERSION_PATCH=0; VERSION_NUMBER=50100; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
 
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-bindings-4.5.0-git to adapt to many kinds of systems.
+'configure' configures radare2-bindings-5.1.0 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -121,6 +126,7 @@ Defaults for the options are specified in brackets.
 Configuration:
   -h, --help              display this help and exit
   -r, --report            show what libs/programs require to work
+  -q, --quiet             be quiet, less verbose (see ./configure -qV)
   -V, --version           display version information and exit
 
 Installation directories:
@@ -157,7 +163,6 @@ printf "
 Some influential environment variables:
   CC          C compiler command
   CFLAGS      C compiler flags
-  CPPFLAGS    C preprocessor flags
   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
               nonstandard directory <lib dir>
   CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
@@ -177,12 +182,26 @@ take_environ() {
 : ${CPP:=cpp}
 : ${CC:=gcc}
 : ${CPP:=cpp}
-: ${CXX:=g++}
+: ${CXX:=c++}
 : ${PREFIX:=/usr/local/}
 }
 
+ochof() {
+	[ "$QUIET" = 1 ] && return
+	printf "$*"
+}
+
+ocho() {
+	[ "$QUIET" = 1 ] && return
+	echo "$*"
+}
+
 show_version() {
-echo "radare2-bindings-4.5.0-git configuration script done with acr v1.8.1.
+if [ "$QUIET" = 1 ]; then
+	echo "5.1.0"
+	exit 0
+fi
+echo "radare2-bindings-5.1.0 configuration script done with acr v1.9.8.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -202,11 +221,16 @@ fi
 case $flag in
 -h|--help|--hel|--h|--he|-help)
 	show_usage ; ;;
+-qV|-quiet-version|--quiet-version)
+	be_quiet
+	show_version ; ;;
+-q|-quiet|--quiet)
+	be_quiet ; ;;
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   radare2-bindings"
-echo "VERSION:   4.5.0-git"
+echo "VERSION:   5.1.0"
 echo "LANGS:     c c++"
 echo "PKG-CONFIG:  r_core"
 echo "FLAGS:     --with-ostype=auto"
@@ -273,25 +297,25 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C CXX CXXFLAGS HAVE_LANG_CXX HAVE_VALABIND VALABIND HAVE_SWIG SWIG HAVE_GIRCOMPILER GIRCOMPILER USEROSTYPE FOO HAVE_PKGCFG_R_CORE"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C CXX CXXFLAGS HAVE_LANG_CXX HAVE_VALABIND VALABIND HAVE_SWIG SWIG HAVE_GIRCOMPILER GIRCOMPILER PKGCONFIG USEROSTYPE FOO HAVE_PKGCFG_R_CORE"
 
 create_environ
 
-echo "checking build system type... ${BUILD}"
-echo "checking host system type... ${HOST}"
-echo "checking target system type... ${TARGET}"
+ocho "checking build system type... ${BUILD}"
+ocho "checking host system type... ${HOST}"
+ocho "checking target system type... ${TARGET}"
 [ "${CROSSBUILD}" = 1 ] && echo "using crosscompilation mode."
 
 #split_host BUILD HOST TARGET
 [ -n "${prefix}" ] && PREFIX="${prefix}"
-echo "checking for working directories... ${WODIS}"
-echo "using prefix '${PREFIX}'"
+ocho "checking for working directories... ${WODIS}"
+ocho "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe test.c test.cxx a.out a.exe"
 
 
 
 COMPILER=CC
-printf "checking for c compiler... "
+ochof "checking for c compiler... "
 HAVE_LANG_C=1
 if [ "${CROSSBUILD}" = 1 ]; then
  (command -v ${HOST}-${CC} >/dev/null 2>&1)
@@ -306,7 +330,7 @@ echo "ERROR: ${CC} cannot create executables" >&2 ;
 exit 1 ; fi
 COMPILER=CXX
 HAVE_LANG_CXX=1
-printf "checking for c++ compiler... "
+ochof "checking for c++ compiler... "
 if [ "${CROSSBUILD}" = 1 ]; then
 (command -v ${HOST}-${CXX} 2>&1 >/dev/null)
 if [ "$?" = 0 ]; then CXX="${HOST}-${CXX}"; fi
@@ -322,7 +346,7 @@ echo "ERROR: ${CXX} cannot create executables" >&2 ;
 do_remove
 exit 1
  fi
-printf "checking for valabind... "
+ochof "checking for valabind... "
 if [ -x "${VALABIND}" ]; then
 	FIND=${VALABIND}
 else
@@ -337,14 +361,18 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_VALABIND=1
 	VALABIND=${FIND}
 else
 	HAVE_VALABIND=0
 	VALABIND=valabind
-echo no ; fi
-printf "checking for swig... "
+if [ "" = 1 ]; then
+echo "Cannot find valabind" >&2
+else
+echo no
+fi ; fi
+ochof "checking for swig... "
 if [ -x "${SWIG}" ]; then
 	FIND=${SWIG}
 else
@@ -359,14 +387,18 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_SWIG=1
 	SWIG=${FIND}
 else
 	HAVE_SWIG=0
 	SWIG=swig
-echo no ; fi
-printf "checking for g-ir-compiler... "
+if [ "" = 1 ]; then
+echo "Cannot find swig" >&2
+else
+echo no
+fi ; fi
+ochof "checking for g-ir-compiler... "
 if [ -x "${GIRCOMPILER}" ]; then
 	FIND=${GIRCOMPILER}
 else
@@ -381,13 +413,44 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_GIRCOMPILER=1
 	GIRCOMPILER=${FIND}
 else
 	HAVE_GIRCOMPILER=0
 	GIRCOMPILER=g-ir-compiler
-echo no ; fi
+if [ "" = 1 ]; then
+echo "Cannot find g-ir-compiler" >&2
+else
+echo no
+fi ; fi
+ochof "checking for pkg-config... "
+if [ -n "$PKGCONFIG" ]; then
+	if [ -x "$PKGCONFIG" ]; then
+		_HAVE_PKGCONFIG="${PKGCONFIG}"
+	else
+		ocho "PKGCONFIG env is not executable"
+		PKGCONFIG=""
+	fi
+else
+	IFS=:
+	for A in ${PATH} ; do
+		if [ -x "${A}/pkg-config" ]; then
+			PKGCONFIG="${A}/pkg-config"
+		elif [ -x "${A}/pkgconf" ]; then
+			PKGCONFIG="${A}/pkgconf"
+		else
+			continue
+		fi
+		break
+	done
+	unset IFS
+fi
+if [ -n "${PKGCONFIG}" ]; then
+	ocho ${PKGCONFIG}
+else
+	echo "Cannot find pkg-config or pkgconf in PATH" >&2
+	exit 1 ocho no; fi
 if [ "$USEROSTYPE" = "auto" ]; then
 if [ "$HOST_OS" = "linux" ]; then
 USEROSTYPE="gnulinux"
@@ -403,8 +466,8 @@ USEROSTYPE="gnulinux"
 else
 if [ "$HOST_OS" = "darwin" ]; then
 USEROSTYPE="darwin"; fi; fi; fi; fi; fi; fi
-[ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
+if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find valid PKGCONFIG, pkg-config or pkgconf in PATH"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_core... '
 tmp=`${PKGCONFIG} --cflags r_core 2>/dev/null`
@@ -442,8 +505,8 @@ if [ -f "${VPATH}/${A}.acr" ]; then
    exit 1
   fi
  fi
- echo "creating ${SD_TARGET}"
-mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
+ ocho "creating ${SD_TARGET}"
+[ "${VPATH}" != '.' ] &&  mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
  cat ${VPATH}/${SD_TARGET}.acr | \
 eval sed -e "s,@VPATH@,${VPATH}/${A},g" ${SEDFLAGS} > ${SD_TARGET}.tmp
 
@@ -462,10 +525,12 @@ done
 done
 
 do_remove
+if [ "$QUIET" = 0 ]; then
 echo
 echo "Final report:"
-for A in  PREFIX HAVE_SWIG HAVE_VALABIND HAVE_GIRCOMPILER ; do # REPORT
+for A in  PREFIX HAVE_SWIG HAVE_VALABIND HAVE_GIRCOMPILER ; do
 eval VAL="\$${A}"
 [ -z "${VAL}" ] && VAL="(null)"
 echo " - ${A} = ${VAL}"
 done
+fi
